language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - cd tests

script: phpunit --configuration phpunit.xml --coverage-text

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true